//
//  UserPagePresenter.swift
//  Task
//
//  Created by Artashes Nok Nok on 3/20/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UserPagePresentationLogic
{
  func presentFetchData(response: UserPage.FetchData.Response)
}

class UserPagePresenter: UserPagePresentationLogic
{
  weak var viewController: UserPageDisplayLogic?
  
  // MARK: Do something
  
  func presentFetchData(response: UserPage.FetchData.Response)
  {
    let viewModel = UserPage.FetchData.ViewModel(userData: response.userElement)
    viewController?.displayFetchData(viewModel: viewModel)
  }
}
