//
//  UsersSortedListPresenter.swift
//  Task
//
//  Created by Artashes Nok Nok on 3/20/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UsersSortedListPresentationLogic
{
  func presentData(response: UsersSortedList.FetchData.Response)
}

class UsersSortedListPresenter: UsersSortedListPresentationLogic
{
  weak var viewController: UsersSortedListDisplayLogic?
  
  // MARK: Do something
  
  func presentData(response: UsersSortedList.FetchData.Response)
  {
    let viewModel = UsersSortedList.FetchData.ViewModel(displeydUserList: response.displeydUserList)
    viewController?.displaySortedData(viewModel: viewModel)
  }
}
