//
//  UsersSortedListRouter.swift
//  Task
//
//  Created by Artashes Nok Nok on 3/20/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UsersSortedListRoutingLogic
{
    func routeToUserPage()
}

protocol UsersSortedListDataPassing
{
  var dataStore: UsersSortedListDataStore? { get set }
}

class UsersSortedListRouter: NSObject, UsersSortedListRoutingLogic, UsersSortedListDataPassing
{
  weak var viewController: UsersSortedListViewController?
  var dataStore: UsersSortedListDataStore?
  
  // MARK: Routing
  
  func routeToUserPage()
  {
    
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "UserPageViewController") as! UserPageViewController
      var destinationDS = destinationVC.router!.dataStore!
    passDataToUserPage(source: dataStore!, destination: &destinationDS)
    navigateToUserPage(source: viewController!, destination: destinationVC)
  }

  // MARK: Navigation
  
  func navigateToUserPage(source: UsersSortedListViewController, destination: UserPageViewController)
  {
    source.present(destination, animated: true, completion: nil)
  }
  
  // MARK: Passing data
  
  func passDataToUserPage(source: UsersSortedListDataStore, destination: inout UserPageDataStore)
  {
    destination.userElement = source.userElement
  }
}
